import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { LineChart, Users, BookOpen, Award, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
export default function ResearchCentreCommerce() {
    return (_jsxs("div", { className: "min-h-screen bg-gray-50", children: [_jsx("div", { className: "bg-[#9E1B32] text-white py-16", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsx("h1", { className: "text-4xl font-serif mb-4", children: "Research Centre in Commerce" }), _jsx("p", { className: "text-lg opacity-90", children: "Advancing business research and economic development" })] }) }), _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 mb-12", children: [_jsx(Link, { to: "/research/areas", className: "group", children: _jsxs("div", { className: "bg-white rounded-xl shadow-sm p-8 transition-all duration-300 ease-in-out hover:shadow-md hover:scale-105", children: [_jsxs("h2", { className: "text-2xl font-serif text-gray-900 mb-6 flex items-center", children: [_jsx(LineChart, { className: "h-6 w-6 text-[#9E1B32] mr-2" }), "Research Areas"] }), _jsx("ul", { className: "space-y-3 text-gray-700 text-lg", children: ['Financial Markets and Investment Analysis', 'Marketing Research and Consumer Behavior', 'Business Strategy and Innovation', 'International Trade and Commerce'].map((item, index) => (_jsxs("li", { className: "flex items-start", children: [_jsx(ArrowRight, { className: "h-5 w-5 text-[#9E1B32] mr-2 mt-1 flex-shrink-0" }), item] }, index))) })] }) }), _jsx(Link, { to: "/research/team", className: "group", children: _jsxs("div", { className: "bg-white rounded-xl shadow-sm p-8 transition-all duration-300 ease-in-out hover:shadow-md hover:scale-105", children: [_jsxs("h2", { className: "text-2xl font-serif text-gray-900 mb-6 flex items-center", children: [_jsx(Users, { className: "h-6 w-6 text-[#9E1B32] mr-2" }), "Research Team"] }), [
                                            { name: 'Dr. Anil Kapoor', role: 'Head of Research Centre' },
                                            { name: 'Dr. Smita Joshi', role: 'Senior Research Fellow' },
                                            { name: 'Dr. Ravi Kumar', role: 'Research Associate' }
                                        ].map((member, index) => (_jsxs("div", { className: "border-b border-gray-200 pb-4", children: [_jsx("h3", { className: "font-medium text-gray-900", children: member.name }), _jsx("p", { className: "text-gray-600", children: member.role })] }, index)))] }) })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8", children: [_jsx(Link, { to: "/research/ResearchPublicationsCommerce/commerce", className: "group", children: _jsxs("div", { className: "bg-white rounded-xl shadow-sm p-8 transition-all duration-300 ease-in-out hover:shadow-md hover:scale-105", children: [_jsxs("h2", { className: "text-2xl font-serif text-gray-900 mb-6 flex items-center", children: [_jsx(BookOpen, { className: "h-6 w-6 text-[#9E1B32] mr-2" }), "Publications"] }), _jsx("p", { className: "text-lg text-gray-700", children: "Our research centre has published in leading commerce journals including:" }), _jsx("ul", { className: "list-disc list-inside space-y-2 ml-4 text-gray-700 text-lg", children: ['Journal of Business Research', 'International Commerce Review', 'Business Strategy Journal', 'Marketing Research Quarterly'].map((journal, index) => (_jsx("li", { children: journal }, index))) })] }) }), _jsx(Link, { to: "/research/achievements", className: "group", children: _jsxs("div", { className: "bg-white rounded-xl shadow-sm p-8 transition-all duration-300 ease-in-out hover:shadow-md hover:scale-105", children: [_jsxs("h2", { className: "text-2xl font-serif text-gray-900 mb-6 flex items-center", children: [_jsx(Award, { className: "h-6 w-6 text-[#9E1B32] mr-2" }), "Achievements"] }), [
                                            { title: 'Best Research Paper Award 2023', description: 'For contributions in Marketing Research' },
                                            { title: 'Excellence in Commerce Research', description: 'Awarded by the Indian Commerce Association' }
                                        ].map((achievement, index) => (_jsxs("div", { className: "border-l-4 border-[#9E1B32] pl-4 mb-4", children: [_jsx("h3", { className: "font-medium text-gray-900", children: achievement.title }), _jsx("p", { className: "text-gray-700", children: achievement.description })] }, index)))] }) })] })] })] }));
}
